In [40]:
import numpy as np

ar = np.array([[4,5,8,4],
               [6,3,2,1],
               [8,6,4,3]])
print (ar.shape)
print (ar.ndim)

(3, 4)
2


In [49]:
arr = np.arange(start=1, stop=10, step=2)
print (arr)
print (arr[3])
print (arr[-1])
print (arr[1:3])
arr[1:3] = 13
print (arr)

[1 3 5 7 9]
7
9
[3 5]
[ 1 13 13  7  9]


In [52]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9] ])
print (arr2d[1, :2])

print (arr2d[2, :1])

print (arr2d[:, :1])

[4 5]
[7]
[[1]
 [4]
 [7]]


In [42]:
a = np.array([[[3, 1],[7, 3]], [[2, 4],[3, 3]]])
print (a[:,0])
print (a.shape)
print (a.ndim)


numpy

list()
[]
pandas
pd.asarray()

[[3 1]
 [2 4]]
(2, 2, 2)
3


In [55]:
arr = np.array([5,67,43,76,2,21])
print (arr.shape)
print (arr.ndim)
arr.sort()
print (arr)

print (a.ndim)

(6,)
1
[ 2  5 21 43 67 76]
3
